version: "3.8"

services:
  db:
    image: mysql:8
    container_name: myflaskapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflaskapp
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/mysql
    # SIN PUERTOS â†’ NO exponemos 3306

  app:
    build: ./webapp
    container_name: myflaskapp_app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: myflaskapp
    depends_on:
      - db
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: myflaskapp_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro

volumes:
  dbdata:
